# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Python\git-hub\Material_Generate\eric6生成GUI\database_input.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Database_Dialog(object):
    def setupUi(self, Database_Dialog):
        Database_Dialog.setObjectName("Database_Dialog")
        Database_Dialog.resize(461, 534)
        #Database_Dialog.setSizeGripEnabled(True)
        self.widget = QtWidgets.QWidget(Database_Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 9, 418, 511))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.db_label = QtWidgets.QLabel(self.widget)
        self.db_label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.db_label.setFont(font)
        self.db_label.setObjectName("db_label")
        self.horizontalLayout.addWidget(self.db_label)
        self.db_name_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.db_name_lineEdit.setMaximumSize(QtCore.QSize(150, 60))
        self.db_name_lineEdit.setObjectName("db_name_lineEdit")
        self.horizontalLayout.addWidget(self.db_name_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.import_excel_pushButton = QtWidgets.QPushButton(self.widget)
        self.import_excel_pushButton.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.import_excel_pushButton.setFont(font)
        self.import_excel_pushButton.setObjectName("import_excel_pushButton")
        self.horizontalLayout.addWidget(self.import_excel_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.db_tableWidget = QtWidgets.QTableWidget(self.widget)
        self.db_tableWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.db_tableWidget.setObjectName("db_tableWidget")
        self.db_tableWidget.setColumnCount(0)
        self.db_tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.db_tableWidget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_pushButton = QtWidgets.QPushButton(self.widget)
        self.add_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.add_pushButton.setFont(font)
        self.add_pushButton.setObjectName("add_pushButton")
        self.horizontalLayout_2.addWidget(self.add_pushButton)
        self.del_pushButton = QtWidgets.QPushButton(self.widget)
        self.del_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.del_pushButton.setFont(font)
        self.del_pushButton.setObjectName("del_pushButton")
        self.horizontalLayout_2.addWidget(self.del_pushButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.db_ok_pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.db_ok_pushButton.setFont(font)
        self.db_ok_pushButton.setObjectName("db_ok_pushButton")
        self.horizontalLayout_3.addWidget(self.db_ok_pushButton)
        self.db_cacel_pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.db_cacel_pushButton.setFont(font)
        self.db_cacel_pushButton.setObjectName("db_cacel_pushButton")
        self.horizontalLayout_3.addWidget(self.db_cacel_pushButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Database_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Database_Dialog)

    def retranslateUi(self, Database_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Database_Dialog.setWindowTitle(_translate("Database_Dialog", "添加数据库"))
        self.db_label.setText(_translate("Database_Dialog", "数据库名称："))
        self.import_excel_pushButton.setText(_translate("Database_Dialog", "导入文本数据"))
        self.add_pushButton.setText(_translate("Database_Dialog", "添加"))
        self.del_pushButton.setText(_translate("Database_Dialog", "删除"))
        self.db_ok_pushButton.setText(_translate("Database_Dialog", "确定"))
        self.db_cacel_pushButton.setText(_translate("Database_Dialog", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Database_Dialog = QtWidgets.QWidget()
    ui = Ui_Database_Dialog()
    ui.setupUi(Database_Dialog)
    Database_Dialog.show()
    sys.exit(app.exec_())

